# -*- coding: utf-8 -*-
"""car_market_trends_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKduskL278s5GMj_HTKewGsYR-GxdcJV
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/1776311302-P3-Car Market Trends Analysis with Car Dekho Data.csv")

# Data cleaning
print("Dataset shape:", df.shape)
print("\nMissing values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

df = df.drop_duplicates().copy()

# Exploratory data analysis
print("\nStatistical summary:\n", df.describe())
print("\nFuel type distribution:\n", df["Fuel_Type"].value_counts())
print("\nTransmission distribution:\n", df["Transmission"].value_counts())
print("\nSeller type distribution:\n", df["Seller_Type"].value_counts())

# 1. Fuel type distribution
fuel_counts = df["Fuel_Type"].value_counts()
plt.figure(figsize=(8, 5))
plt.bar(fuel_counts.index, fuel_counts.values)
plt.title("Number of Cars by Fuel Type")
plt.xlabel("Fuel Type")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# 2. Selling price by transmission
plt.figure(figsize=(8, 5))
transmission_types = df["Transmission"].unique()
groups = [df.loc[df["Transmission"] == t, "Selling_Price"] for t in transmission_types]
plt.boxplot(groups, tick_labels=transmission_types)
plt.title("Selling Price by Transmission")
plt.xlabel("Transmission")
plt.ylabel("Selling Price (Lakhs)")
plt.tight_layout()
plt.show()

# 3. Selling price by seller type
plt.figure(figsize=(8, 5))
seller_types = df["Seller_Type"].unique()
groups = [df.loc[df["Seller_Type"] == t, "Selling_Price"] for t in seller_types]
plt.boxplot(groups, tick_labels=seller_types)
plt.title("Selling Price by Seller Type")
plt.xlabel("Seller Type")
plt.ylabel("Selling Price (Lakhs)")
plt.tight_layout()
plt.show()

# 4. Year vs selling price using Seaborn
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x="Year", y="Selling_Price", hue="Fuel_Type")
plt.title("Year vs Selling Price")
plt.xlabel("Manufacturing Year")
plt.ylabel("Selling Price (Lakhs)")
plt.tight_layout()
plt.show()

# 5. Correlation heatmap using Seaborn
numeric_cols = ["Year", "Selling_Price", "Present_Price", "Kms_Driven", "Owner"]
plt.figure(figsize=(8, 5))
sns.heatmap(df[numeric_cols].corr(), annot=True, fmt=".2f")
plt.title("Correlation Between Numerical Features")
plt.tight_layout()
plt.show()

# Key findings
print("\nAverage selling price:", round(df["Selling_Price"].mean(), 2), "Lakhs")
print("Most common fuel type:", df["Fuel_Type"].mode()[0])
print("Most common transmission:", df["Transmission"].mode()[0])
print("Most common seller type:", df["Seller_Type"].mode()[0])











